# Generated by Django 5.0.4 on 2024-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='mensaje',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
