# Generated by Django 5.0.4 on 2024-05-26 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obra_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='obras'),
            preserve_default=False,
        ),
    ]
