# Generated by Django 5.0.6 on 2024-06-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_obra_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=100)),
                ('obras', models.CharField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_obras', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ManyToManyField(to='core.obra')),
            ],
        ),
    ]
