# Generated by Django 5.0.6 on 2024-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historial_carritocompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fue_comprado',
            field=models.BooleanField(default=False),
        ),
    ]
