# Generated by Django 5.0.6 on 2024-06-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_obra_fue_comprado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.RenameField(
            model_name='carritocompras',
            old_name='obra',
            new_name='obras',
        ),
    ]
