# Generated by Django 5.0.6 on 2024-06-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_historial_rename_obra_carritocompras_obras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='obras',
            field=models.ManyToManyField(blank=True, null=True, to='core.obra'),
        ),
    ]
